import java.util.*;
import javax.swing.JLabel;
public class ProfileForm extends javax.swing.JFrame {

    /**
     * Creates new form ProfileService
     */
    public ProfileForm() {
        initComponents();
        
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_changeaddress = new javax.swing.JButton();
        btn_changephone = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        lbl_Profile = new javax.swing.JLabel();
        btn_order = new javax.swing.JButton();
        lbl_phonee = new javax.swing.JLabel();
        lbl_addresss = new javax.swing.JLabel();
        lbl_usernames = new javax.swing.JLabel();
        lbl_phone = new javax.swing.JLabel();
        lbl_address = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        lbl_userid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(840, 580));
        setResizable(false);
        setSize(new java.awt.Dimension(850, 585));
        getContentPane().setLayout(null);

        btn_changeaddress.setBackground(new java.awt.Color(255, 0, 0));
        btn_changeaddress.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_changeaddress.setForeground(new java.awt.Color(255, 255, 255));
        btn_changeaddress.setText("เปลี่ยนที่อยู่จัดส่ง");
        btn_changeaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changeaddressActionPerformed(evt);
            }
        });
        getContentPane().add(btn_changeaddress);
        btn_changeaddress.setBounds(650, 300, 140, 40);

        btn_changephone.setBackground(new java.awt.Color(255, 0, 0));
        btn_changephone.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_changephone.setForeground(new java.awt.Color(255, 255, 255));
        btn_changephone.setText("เปลี่ยนเบอร์โทร");
        btn_changephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changephoneActionPerformed(evt);
            }
        });
        getContentPane().add(btn_changephone);
        btn_changephone.setBounds(650, 350, 140, 40);

        btn_back.setBackground(new java.awt.Color(255, 0, 0));
        btn_back.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back);
        btn_back.setBounds(30, 490, 100, 30);

        lbl_Profile.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_Profile.setText("Profile");
        getContentPane().add(lbl_Profile);
        lbl_Profile.setBounds(40, 30, 119, 44);

        btn_order.setBackground(new java.awt.Color(34, 167, 240));
        btn_order.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_order.setForeground(new java.awt.Color(255, 255, 255));
        btn_order.setText("รายการสั่งสินค้า");
        btn_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_orderActionPerformed(evt);
            }
        });
        getContentPane().add(btn_order);
        btn_order.setBounds(510, 40, 130, 30);

        lbl_phonee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_phonee.setText("Phone :");
        getContentPane().add(lbl_phonee);
        lbl_phonee.setBounds(100, 370, 90, 22);

        lbl_addresss.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_addresss.setText("Address :");
        getContentPane().add(lbl_addresss);
        lbl_addresss.setBounds(100, 320, 110, 22);

        lbl_usernames.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_usernames.setText("Username :");
        getContentPane().add(lbl_usernames);
        lbl_usernames.setBounds(100, 270, 110, 22);

        lbl_phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_phone.setText("...");
        getContentPane().add(lbl_phone);
        lbl_phone.setBounds(240, 360, 390, 40);

        lbl_address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_address.setText("...");
        getContentPane().add(lbl_address);
        lbl_address.setBounds(240, 310, 390, 40);

        lbl_username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_username.setText("...");
        getContentPane().add(lbl_username);
        lbl_username.setBounds(240, 260, 390, 40);
        getContentPane().add(lbl_userid);
        lbl_userid.setBounds(270, 80, 110, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_changephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changephoneActionPerformed
        // TODO add your handling code here:
        ProfileService.showChangePhoneForm();
        this.hide();
    }//GEN-LAST:event_btn_changephoneActionPerformed

    private void btn_changeaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changeaddressActionPerformed
        // TODO add your handling code here:
        ProfileService.showChangeAddressForm();
        this.hide();
         
        
    }//GEN-LAST:event_btn_changeaddressActionPerformed

    private void btn_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_orderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_orderActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        ProfileService.showMainPageForm();
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    public static void main(String args[]) {
       
           
                
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileForm().setVisible(true); 
                 
        
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_changeaddress;
    private javax.swing.JButton btn_changephone;
    private javax.swing.JButton btn_order;
    private javax.swing.JLabel lbl_Profile;
    public static javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_addresss;
    public static javax.swing.JLabel lbl_phone;
    private javax.swing.JLabel lbl_phonee;
    public static javax.swing.JTextField lbl_userid;
    public static javax.swing.JLabel lbl_username;
    private javax.swing.JLabel lbl_usernames;
    // End of variables declaration//GEN-END:variables

    
}
